
version: '3.9'
services:
  api:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/babytracker?sslmode=disable
    depends_on:
      - db
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: babytracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
